import { writeFileSync } from "fs";
import { resolveMetricsToken, METRICS_TOKEN_KEY } from "./metrics.js";
import type { EnvVar, ExcelParseResult, RawEnvRecord, VercelEnvironment } from "./types.js";

const ALL_ENVS: VercelEnvironment[] = ["production", "preview", "development"];

// Never upload these to Vercel — scripts-only or CI-only secrets
const FORBIDDEN = new Set([
  "SUPABASE_SERVICE_ROLE_KEY",
  "SENTRY_AUTH_TOKEN",
]);

// Keys that also need a NEXT_PUBLIC_ prefixed counterpart
const AUTO_PUBLIC: Record<string, string> = {
  SUPABASE_URL: "NEXT_PUBLIC_SUPABASE_URL",
  SUPABASE_ANON_KEY: "NEXT_PUBLIC_SUPABASE_ANON_KEY",
  SENTRY_DSN: "NEXT_PUBLIC_SENTRY_DSN",
};

// Static values derived from project config (not in Excel)
const STATIC_VARS: RawEnvRecord[] = [
  {
    key: "NEXT_PUBLIC_APP_URL",
    value: "https://eunoia-ai-os-platform.vercel.app",
    source: "static:config",
  },
];

function makeEnvVar(key: string, value: string, generated = false): EnvVar {
  return {
    key,
    value,
    environments: ALL_ENVS,
    forbidden: FORBIDDEN.has(key),
    generated,
  };
}

export function buildEnvVars(parsed: ExcelParseResult): EnvVar[] {
  const byKey = new Map<string, RawEnvRecord>();

  // Static vars first (lowest priority)
  for (const r of STATIC_VARS) {
    byKey.set(r.key, r);
  }
  // Excel vars override statics
  for (const r of parsed.records) {
    byKey.set(r.key, r);
  }

  const vars: EnvVar[] = [];
  const seenKeys = new Set<string>();

  for (const [key, record] of byKey) {
    if (seenKeys.has(key)) continue;
    seenKeys.add(key);
    vars.push(makeEnvVar(key, record.value));

    // Expand NEXT_PUBLIC_ counterpart if not already present
    const publicKey = AUTO_PUBLIC[key];
    if (publicKey && !seenKeys.has(publicKey)) {
      seenKeys.add(publicKey);
      vars.push(makeEnvVar(publicKey, record.value));
    }
  }

  // Resolve METRICS_TOKEN (generate if missing/trivial)
  const existing = byKey.get(METRICS_TOKEN_KEY);
  const { value: metricsValue, generated } = resolveMetricsToken(existing?.value);
  if (!seenKeys.has(METRICS_TOKEN_KEY)) {
    vars.push(makeEnvVar(METRICS_TOKEN_KEY, metricsValue, generated));
  } else {
    const idx = vars.findIndex((v) => v.key === METRICS_TOKEN_KEY);
    if (idx >= 0) {
      const { value: resolved, generated: gen } = resolveMetricsToken(vars[idx].value);
      vars[idx] = { ...vars[idx], value: resolved, generated: gen };
    }
  }

  return vars;
}

export function writeEnvFile(vars: EnvVar[], outputPath: string): void {
  const lines: string[] = [
    `# .env.production.master`,
    `# Generated by tools/bootstrap on ${new Date().toISOString()}`,
    `# DO NOT COMMIT — this file is .gitignored`,
    ``,
    `# ─── Forbidden (never upload to Vercel) ──────────────────────────`,
  ];

  const forbidden = vars.filter((v) => v.forbidden);
  const allowed = vars.filter((v) => !v.forbidden);

  for (const v of forbidden) {
    lines.push(`# ${v.key}=${v.value}`);
  }

  lines.push(``, `# ─── All environments ────────────────────────────────────────────`);

  for (const v of allowed) {
    const suffix = v.generated ? "  # auto-generated" : "";
    lines.push(`${v.key}=${v.value}${suffix}`);
  }

  lines.push(``);
  writeFileSync(outputPath, lines.join("\n"), "utf8");
}
